name: android
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - uses: android-actions/setup-android@v2
      - uses: actions/setup-go@v4
      - name: build
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go get golang.org/x/mobile/bind
          gomobile init
          go run ./cmd/internal/build_libbox
      - uses: softprops/action-gh-release@v1
        with:
          files: libbox.aar
